Overload == and != in Room and Hotel
mezidia/Basics-Of-Software-Development-On-.Net pull request #17
Opened 2021-03-31 19:44 UTC by fhrr-sht

2021-03-31 19:46 UTC, VsIG-official commented
Also, You need to check 'em in [Programm.cs]

2021-03-31 19:49 UTC, VsIG-official requested changes
As I said earlier, check this functions in [Program.cs], as We did

2021-03-31 22:19 UTC, fhrr-sht commented
на їж

2021-04-01 07:40 UTC, VsIG-official approved these changes

2021-04-01 07:40 UTC, VsIG-official commented on Lab4/Project/Program.cs
> +			RedHotel.Rating = 23;
And why did You change this field?
You just broke Maxim's test

2021-04-01 07:59 UTC, merged